# Generated by Django 4.0.2 on 2022-02-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcompython', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='dataDoUpLoad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
